tplProjectName: mobilebuilder_tpl_8_0_0_ngx
↓FCMPushNotifications [ngx.components.UIActionStack-1591517891678]: 🗏 mobileSharedActions/FCMPushNotifications.yaml
↓DemoPage [ngx.components.PageComponent-1591517856447]: 🗏 mobilePages/DemoPage.yaml